#!/usr/bin/env python3
'''
## Licensing Model

You may use this **Research Document** under **ONE** of the following options:

### 🔓 Option A — Open License (Non-Commercial)

- License: **AGPL-3.0**
- Permitted use:
  - Personal, educational, academic, and research purposes.
- Obligations:
  - Publish any modifications or derivatives.
  - Maintain the same license.
  - Share the full modified Research Document,
    including when used in hosted or online platforms.
- ❌ Commercial use is not permitted.

### 💼 Option B — Commercial License

- Required for any for-profit or monetized use.
- Permits:
  - Proprietary or confidential use.
  - Commercial platforms and services.
  - Internal corporate or institutional deployment.
- Requires an explicit agreement with the author.

See full details in:
- `LICENSE`
- `COMMERCIAL.md`

'''

"""Convert a HESS-style solution file into a DIMACS-style boolean model line."""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path
from typing import Iterable, Sequence, Tuple

Literal = Tuple[int, int]


def read_solution(path: Path) -> Sequence[Literal]:
    content = path.read_text(encoding="utf-8").strip()
    if not content:
        raise ValueError("solution file is empty")
    obj = ast.literal_eval(content)
    if not isinstance(obj, list):
        raise ValueError("solution must be a list of tuples")
    parsed: list[Literal] = []
    for item in obj:
        if not (
            isinstance(item, tuple)
            and len(item) == 2
            and isinstance(item[0], int)
            and isinstance(item[1], int)
        ):
            raise ValueError(f"bad entry in solution: {item!r}")
        parsed.append((item[0], item[1]))
    return parsed


def to_cnf_model(assignments: Iterable[Literal]) -> str:
    """Produce DIMACS-style assignment line ending with '0'."""
    literals: list[int] = []
    for var, val in assignments:
        if var == 0:
            raise ValueError("variable index must be nonzero")
        lit = var if val else -var
        literals.append(lit)
    return " ".join(str(lit) for lit in literals) + " 0"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Turn [(var,val), ...] into a CNF literal list (1 -2 3 ... 0)."
    )
    parser.add_argument(
        "--sol",
        required=True,
        type=Path,
        help="Path to solution file generated by hess_cdcl.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Destination for the CNF assignment (defaults to stdout).",
    )
    args = parser.parse_args()

    assignments = read_solution(args.sol)
    model_line = to_cnf_model(assignments)

    if args.out:
        args.out.write_text("v SATSIFIABLE\n", encoding="utf-8")
        args.out.write_text(model_line + "\n", encoding="utf-8")
    else:
        print("c SATSIFIABLE")
        print('v ' + model_line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
